### PR TITLE
More helpful usage errors

### LINKED ISSUE #372: Confusing help/debug message for payment_intents/confirm
### Issue
I was trying to confirm a Payment Intent. My command was wrong, but the error message I got didn't really help me get back on track:
```
> stripe payment_intents confirm -d payment_method=pm_some_token -d return_url="https://example.com"
confirm only takes 1 argument. See `stripe confirm --help` for supported flags and usage
```
"Only takes 1 argument" suggests to me that one of those two `-d` flagged options shouldn't be there. In reality, it's complaining that I haven't added the Payment Intent token like so:
```
stripe payment_intents confirm pi_some_token
```

Moreover, `stripe confirm --help` doesn't work:
```
> stripe confirm --help
Unknown command "confirm" for "stripe". Did you mean "config"?
If not, see "stripe --help" for a list of available commands.
```
### Expected Behavior
I'd expect `stripe confirm --help` to give a standard help/man type page. The generic error message for confirming the PI itself could also be improved.

### Steps to reproduce
Rerun the commands above on `stripe version 1.3.2`.

### Traceback
N/A

### Environment
macOS, though not applicable

### PR DESCRIPTION
**Pull request by richardm-stripe**
### Reviewers
r? @tomer-stripe 

 ### Summary
Fixes #372 

**Before:**
```shell
$ stripe logs tail foo
tail does not take any arguments. See `stripe tail --help` for supported flags and usage
```
**After:**
```shell
$ go run cmd/stripe/main.go logs tail foo
`stripe logs tail` does not take any positional arguments. See `stripe logs tail --help` for supported flags and usage
```

**Before:**
```shell
$ stripe samples create foo foo foo
create only takes 2 arguments (or less). See `stripe create --help` for supported flags and usage
```
**After:**
```shell
$ stripe samples create foo foo foo
`stripe samples create` accepts at maximum 2 positional arguments. See `stripe samples create --help` for supported flags and usage
```

**Before:**
```shell
$ stripe customers delete
delete only takes 1 argument. See `stripe delete --help` for supported flags and usage
```
**After:**
```shell
$ stripe customers delete
`stripe customers delete` requires exactly 1 positional argument. See `stripe customers delete --help` for supported flags and usage
```

### CODE REVIEW

**Comment by tomer-stripe** [comment]
@richardm-stripe could you run the payment intent commands in the original issue and share what the output is?

**Comment by richardm-stripe** [comment]
Before:
```shell
$ stripe payment_intents confirm -d payment_method=pm_some_token -d return_url="https://example.com"
confirm only takes 1 argument. See `stripe confirm --help` for supported flags and usage
```
After:
```shell
$ stripe payment_intents confirm -d payment_method=pm_some_token -d return_url="https://example.com"
`stripe payment_intents confirm` requires exactly 1 positional argument. See `stripe payment_intents confirm --help` for supported flags and usage
```

**Comment by richardm-stripe** [comment]
ptal @tomer-stripe

File: pkg/validators/cmds.go [hunk 1]
```diff
@@ -26,17 +26,17 @@ func NoArgs(cmd *cobra.Command, args []string) error {
 // is different than the arguments passed in
 func ExactArgs(num int) cobra.PositionalArgs {
 	return func(cmd *cobra.Command, args []string) error {
-		argument := "argument"
-		if num > 1 {
-			argument = "arguments"
+		argument := "positional argument"
+		if num != 1 {
+			argument = "positional arguments"
```
Comment (tomer-stripe) [inline pkg/validators/cmds.go:31]: *shakes fist* English
