### PR TITLE
Better synchronization for websocket commands

### LINKED ISSUE #156: stripe listen does not log when it cannot create a websocket connection
### Issue
I'm not sure why `stripe listen` isn't working - maybe the endpoint is down or I've made a mistake (it was working earlier with no changes on my end). 

Regardless, it's super confusing that the CLI says "Ready! Your webhook signing secret..." when in fact the CLI is silently dialing the websocket endpoint and repeatedly failing.

### Expected Behavior
I expected the `stripe listen` to log its connection failures / retries (without having to run the command with `--log-level=debug`).

### Steps to reproduce
Run `stripe listen` in such a way that it authenticates properly but can't create a websocket connection to stripe-cli.stripe.com.

### Traceback
```
stripe listen --forward-to localhost:4000/webhooks/stripeaccountupdated --print-json --log-level debug
⣾ Getting ready... [Tue, 10 Sep 2019 20:42:17 EDT] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⡿ Getting ready... [Tue, 10 Sep 2019 20:42:27 EDT] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe display_connect_filter_warning=false reconnect_delay=36 websocket_authorized_feature=webhook-payloads websocket_id={ws-id}websocket_url=wss://stripe-cli.stripe.com/subscribe/{account}
[Tue, 10 Sep 2019 20:42:27 EDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
> Ready! Your webhook signing secret is {secret} (^C to quit)
[Tue, 10 Sep 2019 20:42:27 EDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/{account}?websocket_feature=webhook-payloads
[Tue, 10 Sep 2019 20:42:37 EDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Tue, 10 Sep 2019 20:42:37 EDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
[Tue, 10 Sep 2019 20:42:47 EDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/{account}?websocket_feature=webhook-payloads
[Tue, 10 Sep 2019 20:42:57 EDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Tue, 10 Sep 2019 20:42:57 EDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
^C[Tue, 10 Sep 2019 20:43:00 EDT] DEBUG proxy.Proxy.Run: Ctrl+C received, cleaning up...
[Tue, 10 Sep 2019 20:43:00 EDT] DEBUG proxy.Proxy.Run: Bye!
```

### Environment
macOS

### PR DESCRIPTION
**Pull request by ob-stripe**
### Reviewers
r? @tomer-stripe 
cc @stripe/dev-platform

 ### Summary
Improves the synchronization of all goroutines in websocket commands:
- create a cancelable [context](https://blog.golang.org/context)
- start a goroutine who will be blocked until Ctrl+C is pressed. When Ctrl+C is pressed, the goroutine cancels the context
- create a goroutine for the session creation request and pass the context to the HTTP client
- block until the goroutine returns
- if the session creation succeeds, pass the context to the websocket client
- block until either the context is canceled or the client is connected
- at this point only, display the success message (previously we would start the websocket client goroutine and immediately display the success message despite the fact that the websocket client was still connecting)

Fixes #156.

Future improvements:
- there's a lot of duplicated code between the proxy and logtailing packages, we should factorize it
- the websocket client still attempts to reconnect endlessly, even when the websocket ID is no longer valid

### CODE REVIEW

File: pkg/logtailing/tailer.go [hunk 1]
```diff
@@ -105,85 +108,134 @@ func New(cfg *Config) *Tailer {
...
+		ansi.StopSpinner(s, "Ready! You're now waiting to receive API request logs (^C to quit)", t.cfg.Log.Out)
+	case <-t.ctx.Done():
+		ansi.StopSpinner(s, "", t.cfg.Log.Out)
+		t.cfg.Log.Fatalf("Aborting")
+	}
 
 	if session.DisplayConnectFilterWarning {
 		color := ansi.Color(os.Stdout)
-		fmt.Println(fmt.Sprintf("%s you specified the 'account' filter for connect accounts but are not a connect merchant, so the filter will not be applied.", color.Yellow("Warning")))
+		fmt.Println(fmt.Sprintf("%s you specified the 'account' filter for Connect accounts but are not a Connect merchant, so the filter will not be applied.", color.Yellow("Warning")))
```
Comment (tomer-stripe) [inline pkg/logtailing/tailer.go]: I know this is unrelated but could we change this to: "Warning: you specified the 'account' filter which applies only to Connect users so it will have no affect."

We don't really talk about `merchants` as a concept externally.
